//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfExtraTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfExtraTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow assembly.
        /// </summary>
        public static string AllowAssembly {
            get {
                return ResourceManager.GetString("AllowAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow degraded print.
        /// </summary>
        public static string AllowDegradedPrint {
            get {
                return ResourceManager.GetString("AllowDegradedPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow fill in.
        /// </summary>
        public static string AllowFillIn {
            get {
                return ResourceManager.GetString("AllowFillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow modify annotations.
        /// </summary>
        public static string AllowModifyAnnotations {
            get {
                return ResourceManager.GetString("AllowModifyAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow modify contents.
        /// </summary>
        public static string AllowModifyContents {
            get {
                return ResourceManager.GetString("AllowModifyContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow print.
        /// </summary>
        public static string AllowPrint {
            get {
                return ResourceManager.GetString("AllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow screen readers.
        /// </summary>
        public static string AllowScreenReaders {
            get {
                return ResourceManager.GetString("AllowScreenReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow text copy.
        /// </summary>
        public static string AllowTextCopy {
            get {
                return ResourceManager.GetString("AllowTextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom center.
        /// </summary>
        public static string BottomCenter {
            get {
                return ResourceManager.GetString("BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI language will change at next application start.
        /// </summary>
        public static string ChangeLanguageNotify {
            get {
                return ResourceManager.GetString("ChangeLanguageNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t leave a blank password.
        /// </summary>
        public static string DontLeaveBlankPassword {
            get {
                return ResourceManager.GetString("DontLeaveBlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract page.
        /// </summary>
        public static string ExtractPage {
            get {
                return ResourceManager.GetString("ExtractPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file have no password.
        /// </summary>
        public static string FileHaveNoPassword {
            get {
                return ResourceManager.GetString("FileHaveNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating preview.
        /// </summary>
        public static string GeneratingPreview {
            get {
                return ResourceManager.GetString("GeneratingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Bottom.
        /// </summary>
        public static string MarginBottom {
            get {
                return ResourceManager.GetString("MarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Left.
        /// </summary>
        public static string MarginLeft {
            get {
                return ResourceManager.GetString("MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Right.
        /// </summary>
        public static string MarginRight {
            get {
                return ResourceManager.GetString("MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Top.
        /// </summary>
        public static string MarginTop {
            get {
                return ResourceManager.GetString("MarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged {0} files, total page of new file: {1} pages.
        /// </summary>
        public static string MergedSuccess {
            get {
                return ResourceManager.GetString("MergedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge files.
        /// </summary>
        public static string MergeFiles {
            get {
                return ResourceManager.GetString("MergeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifed date.
        /// </summary>
        public static string ModifedDate {
            get {
                return ResourceManager.GetString("ModifedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string NavigationViewGroup1 {
            get {
                return ResourceManager.GetString("NavigationViewGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string NavigationViewGroup2 {
            get {
                return ResourceManager.GetString("NavigationViewGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge and Extraction.
        /// </summary>
        public static string NavigationViewGroup3 {
            get {
                return ResourceManager.GetString("NavigationViewGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open now.
        /// </summary>
        public static string OpenNow {
            get {
                return ResourceManager.GetString("OpenNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page rotation.
        /// </summary>
        public static string PageRotate {
            get {
                return ResourceManager.GetString("PageRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging.
        /// </summary>
        public static string Paging {
            get {
                return ResourceManager.GetString("Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file was added page number. (if your file have password, it automatically remove).
        /// </summary>
        public static string PagingComplete {
            get {
                return ResourceManager.GetString("PagingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needed to open this file.
        /// </summary>
        public static string PasswordRequirement {
            get {
                return ResourceManager.GetString("PasswordRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharse.
        /// </summary>
        public static string Pharse {
            get {
                return ResourceManager.GetString("Pharse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file was protected with password.
        /// </summary>
        public static string ProtectedSuccess {
            get {
                return ResourceManager.GetString("ProtectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect password.
        /// </summary>
        public static string ProtectPassword {
            get {
                return ResourceManager.GetString("ProtectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to restart application to apply your selected language..
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation (degree).
        /// </summary>
        public static string RotationDegree {
            get {
                return ResourceManager.GetString("RotationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as ....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save change.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file was saved successfully at: {0}.
        /// </summary>
        public static string SaveSucess {
            get {
                return ResourceManager.GetString("SaveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the PDF file.
        /// </summary>
        public static string SelectPdfFile {
            get {
                return ResourceManager.GetString("SelectPdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamping.
        /// </summary>
        public static string Stamp {
            get {
                return ResourceManager.GetString("Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top center.
        /// </summary>
        public static string TopCenter {
            get {
                return ResourceManager.GetString("TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string TopLeft {
            get {
                return ResourceManager.GetString("TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total page: {0}.
        /// </summary>
        public static string TotalPage {
            get {
                return ResourceManager.GetString("TotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file.
        /// </summary>
        public static string UnableToOpenFile {
            get {
                return ResourceManager.GetString("UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotect file.
        /// </summary>
        public static string UnprotectFile {
            get {
                return ResourceManager.GetString("UnprotectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotect file successfully.
        /// </summary>
        public static string UnProtectSuccess {
            get {
                return ResourceManager.GetString("UnProtectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotect.
        /// </summary>
        public static string UnsetPassword {
            get {
                return ResourceManager.GetString("UnsetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
